#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    cooldown:
      default-days: 1
    groups:
      lint:
        patterns:
          - "eslint*"
          - "@next/eslint*"
      react-deps:
        patterns:
          - "react"
          - "react-dom"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
