minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - next@16.0.10
  - "@next/env@16.0.10"
  - "@next/eslint-plugin-next@16.0.10"
  - eslint-config-next@16.0.10
  - react@19.2.3
  - react-dom@19.2.3

onlyBuiltDependencies:
  - better-sqlite3
